# Build and profile the C++ code
name: Check build

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"


jobs:
  check_build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Let conan generate a default profile
        run: conan profile detect

      - name: Use conan to install boost
        run: conan install . --output-folder=build --build=missing


      # Do not overwrite the conan file
      #- name: Set up CMake build folder for release mode, thanks https://stackoverflow.com/a/64719718
      #  run: cmake -B build . -DCMAKE_BUILD_TYPE=Release 

      #- name: Run CMake
      #  run: cmake --build build 

      - name: Run CMake, from https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .


      - name: Run the program
        run: ./build/gha_cmake_gcc_cpp17_gprof

      - name: Produce the gprof log
        run: gprof ./build/gha_cmake_gcc_cpp17_gprof > gprof.log

      - name: Read the 100 top lines
        run: head gprof.log -n 100

      - name: Get g++ version
        run: g++ --version
